##
# docker-compose.yml
#
# Declares supporting services of flask app
# created: NOV 2020
#
##

version: "3.7"

services:
  # start Flask app from docker-compose file
  ml_flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    image:  ecast229/ml_flask_app:latest
    ports:
        - "${FLASK_PORT:-5000}:5000"

  # Use Airflow as pipeline engine for ML workflow
  # use postgres as back-end for airflow
  postgres_airflow:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  # set up airflow scheduler, depends on postgres back-end
  scheduler_airflow:
    image: apache/airflow
    command: scheduler
    restart: on-failure
    depends_on:
      - postgres_airflow
    env_file:
      - .env
    #volumes:
    #  - ./dags:/opt/airflow/dags
    #  - ./logs:/opt/airflow/logs

  # set up airflow webserver, depends on postgres back-end and scheduler  
  webserver_airflow:
    image: apache/airflow
    entrypoint: entrypoint.sh
    restart: on-failure
    depends_on:
      - postgres_airflow
      - scheduler_airflow
    env_file:
      - .env
    #volumes:
    #  - ./dags:/opt/airflow/dags
    #  - ./logs:/opt/airflow/logs
    #  - ./scripts:/opt/airflow/scripts
    ports:
      - "${WEBSERVER_PORT:-8080}:8080"




